import './globals.css';

import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from '@tanstack/react-query';
import type { Metadata } from 'next';
import { Lato } from 'next/font/google';

import Footer from '@/components/footer';
import Header from '@/components/header';
import QueryProvider from '@/components/providers/query-provider';
import { getMe } from '@/lib';

const lato = Lato({
  weight: ['300', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ['me'],
    queryFn: getMe,
  });

  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        <QueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Header />
          </HydrationBoundary>
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
