import './globals.css';

import type { Metadata } from 'next';
import { Lato } from 'next/font/google';

import Footer from '@/components/footer';
import Header from '@/components/header';
import QueryProvider from '@/components/providers/query-provider';

const lato = Lato({
  weight: ['300', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        <QueryProvider>
          <Header />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
